name: myfo
description: "my favorite objects"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2 # 상태 관리 패키지
  shared_preferences: ^2.1.1
  uuid: ^3.0.6 # 고유 ID 생성 패키지
  intl: ^0.19.0
  google_fonts: ^4.0.0
  image_picker: ^1.1.2
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.2
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.4.3
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/images/myfo_splash_screen.png # 스플래시 이미지 경로
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/myfo_icon@3x.png"

flutter:
  uses-material-design: true
#  assets:
#    - .env
  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Paperlogy-8ExtraBold.ttf
          weight: 800